- name: Set the hostname
  become: yes
  hostname:
    name: vpn.server

- name: Enable IPv4 traffic forwarding
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
