- name: Install OpenVPN and configure it
  hosts: vpn_public
  user: ubuntu
  become_method: sudo
  connection: ssh
  gather_facts: no

  roles:
    - common
    - openvpn
    - dnsmasq
    - { role: openvpn-add-client, when: (username is defined) and (output is defined) }
