- name: Enable IPv4 traffic forwarding
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Set forward policy
  become: yes
  lineinfile:
    dest: /etc/default/ufw
    line: DEFAULT_FORWARD_POLICY="ACCEPT"
    regexp: "^DEFAULT_FORWARD_POLICY\\="

- name: Copy ufw before.rules
  become: yes
  template:
    src: before.rules.j2
    dest: /etc/ufw/before.rules

- name: Restart ufw
  become: yes
  service:
    name: "ufw"
    enabled: yes
    state: restarted
